CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    first_name character varying(30) COLLATE pg_catalog."default",
    last_name character varying(40) COLLATE pg_catalog."default",
    login character varying(20) COLLATE pg_catalog."default" NOT NULL,
    email character varying(40) COLLATE pg_catalog."default",
    image character varying(200) COLLATE pg_catalog."default",
    registration_date date DEFAULT now(),
    status_id integer DEFAULT 2,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT user_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;